name: build-and-publish-bottles

# ──────────────────────────────
# Required permissions
# ──────────────────────────────
permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

# ──────────────────────────────
# Triggers
# ──────────────────────────────
on:
  push:
    paths:
      - "Formula/zkstack.rb"
  workflow_dispatch:

# ──────────────────────────────
# Global env – speed up CI
# ──────────────────────────────
env:
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

# ──────────────────────────────
# 1. Build bottles on every OS
# ──────────────────────────────
jobs:
  build:
    name: Build bottles (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-latest, macos-13, ubuntu-22.04, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Prepare dirs
        run: |
          # 1. Define paths as normal shell vars
          BOTTLES_DIR="$GITHUB_WORKSPACE/bottles"
          LOGS_DIR="$BOTTLES_DIR/logs"

          # 2. Create the directories right away
          mkdir -p "$BOTTLES_DIR" "$LOGS_DIR"

          # 3. Export for subsequent steps
          echo "BOTTLES_DIR=$BOTTLES_DIR" >> "$GITHUB_ENV"
          echo "LOGS_DIR=$LOGS_DIR"       >> "$GITHUB_ENV"


      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Build and bottle zkstack
        run: |
          brew test-bot \
            --only-formulae \
            --keep-old \
            --only-json-tab \
            --skip-online-checks \
            zkstack
          mv *.bottle.* "$BOTTLES_DIR/"

      - uses: actions/upload-artifact@v4
        with:
          name: bottles-${{ matrix.runner }}
          path: ${{ env.BOTTLES_DIR }}/*

# ──────────────────────────────
# 2. Aggregate + publish + commit
# ──────────────────────────────
  publish:
    name: Publish & commit bottles
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Prepare dirs
        run: |
          # 1. Define paths as normal shell vars
          BOTTLES_DIR="$GITHUB_WORKSPACE/bottles"
          LOGS_DIR="$BOTTLES_DIR/logs"

          # 2. Create the directories right away
          mkdir -p "$BOTTLES_DIR" "$LOGS_DIR"

          # 3. Export for subsequent steps
          echo "BOTTLES_DIR=$BOTTLES_DIR" >> "$GITHUB_ENV"
          echo "LOGS_DIR=$LOGS_DIR"       >> "$GITHUB_ENV"


      - uses: actions/download-artifact@v4
        with:
          pattern: bottles-*            # grabs all runner artifacts
          merge-multiple: true          # extracts *into* bottles-${id}/
          path: ${{ env.BOTTLES_DIR }}

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Publish bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.PAT_PUSH }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ secrets.PAT_PUSH }}
        uses: Homebrew/actions/post-build@main
        with:
          bottles-directory: ${{ env.BOTTLES_DIR }}
          logs-directory: ${{ env.LOGS_DIR }} 
          runner: ubuntu-latest
          upload-bottles: true
          cleanup: false
