name: build-and-publish-bottles

# ──────────────────────────────
# Required permissions
# ──────────────────────────────
permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

# ──────────────────────────────
# Triggers
# ──────────────────────────────
on:
  push:
    paths:
      - "Formula/zkstack.rb"
  workflow_dispatch:

# ──────────────────────────────
# Global env – speed up CI
# ──────────────────────────────
env:
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

# ──────────────────────────────
# 1. Build bottles on every OS
# ──────────────────────────────
jobs:
  build:
    name: Build bottles (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-latest, macos-13, ubuntu-22.04, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Build bottle
        run: |
          brew install --build-bottle Formula/zkstack.rb
          mkdir ${{ github.workspace }}/bottles
          brew bottle --json zkstack
          mv *.bottle.* ${{ github.workspace }}/bottles

      - name: Upload bottle artifact
        uses: actions/upload-artifact@v4
        with:
          name: bottles-${{ matrix.runner }}
          path: ${{ github.workspace }}/bottles

# ──────────────────────────────
# 2. Aggregate + publish + commit
# ──────────────────────────────
  publish:
    name: Publish & commit bottles
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download bottle artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/bottles
          pattern: bottles-*
          merge-multiple: true

      - name: Move bottles into tap root
        run: |
          mv ${{ github.workspace }}/bottles/* ${{ github.workspace }}/
          rmdir ${{ github.workspace }}/bottles

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Publish bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.PAT_PUSH }}
        uses: Homebrew/actions/post-build@main
        with:
          bottles-directory: .
          logs-directory: .
          runner: ubuntu-latest
          upload-bottles: true
          cleanup: false
