name: Build & Upload Bottles

permissions:
  contents: write
  id-token: write
  attestations: write
  packages: write

on:
  push:
    paths: [ "Formula/zkstack.rb" ]
  workflow_dispatch:

env:
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

jobs:
  bottle:
    name: Build Bottles
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-13, ubuntu-latest, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4

      - uses: Homebrew/actions/setup-homebrew@main

      - name: Build bottle
        run: |
          brew install --build-bottle --formula Formula/zkstack.rb
          mkdir bottles
          brew bottle --json zkstack
          mv *.bottle.* bottles/

      - name: Publish bottles
        uses: Homebrew/actions/post-build@main
        with:
          bottles-directory: bottles
          logs-directory: .
          runner: ${{ matrix.os }}
          cleanup: true
